spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    useSSL: false
    url: jdbc:mysql://127.0.0.1:3306/dbtank
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true